import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/db";
import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: "#f97316",
    paddingBottom: 16,
  },
  logo: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#f97316",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 8,
  },
  meta: {
    fontSize: 9,
    color: "#666",
    marginTop: 4,
  },
  scoreSection: {
    flexDirection: "row",
    marginBottom: 24,
    gap: 16,
  },
  scoreBox: {
    width: 80,
    height: 80,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1f2937",
  },
  scoreValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#fff",
  },
  gradeValue: {
    fontSize: 14,
    color: "#9ca3af",
  },
  issuesSection: {
    marginTop: 16,
  },
  issuesTitle: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 8,
  },
  issueRow: {
    flexDirection: "row",
    marginBottom: 6,
    padding: 8,
    backgroundColor: "#f9fafb",
  },
  issueType: {
    width: 60,
    fontSize: 8,
    textTransform: "uppercase",
  },
  issueContent: {
    flex: 1,
  },
  issueMsg: {
    fontWeight: "bold",
    marginBottom: 2,
  },
  issueCat: {
    fontSize: 8,
    color: "#6b7280",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#9ca3af",
    textAlign: "center",
  },
});

function AuditPDF({
  companyName,
  url,
  score,
  grade,
  issues,
  pagesAudited,
}: {
  companyName: string;
  url: string;
  score: number;
  grade: string;
  issues: { type: string; category: string; message: string; details?: string }[];
  pagesAudited: number;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.logo}>
            {companyName || "AlChemist_SEO"}
          </Text>
          <Text style={styles.title}>SEO Audit Report</Text>
          <Text style={styles.meta}>
            {url} • {pagesAudited} page{pagesAudited > 1 ? "s" : ""} audited •{" "}
            {new Date().toLocaleDateString()}
          </Text>
        </View>

        <View style={styles.scoreSection}>
          <View style={[styles.scoreBox, { backgroundColor: "#065f46" }]}>
            <Text style={styles.scoreValue}>{score}</Text>
            <Text style={styles.gradeValue}>/100</Text>
          </View>
          <View style={[styles.scoreBox, { backgroundColor: "#1e40af" }]}>
            <Text style={[styles.scoreValue, { fontSize: 36 }]}>{grade}</Text>
            <Text style={styles.gradeValue}>Grade</Text>
          </View>
        </View>

        <View style={styles.issuesSection}>
          <Text style={styles.issuesTitle}>Issues Found</Text>
          {issues.map((issue, i) => (
            <View key={i} style={styles.issueRow}>
              <Text
                style={[
                  styles.issueType,
                  {
                    color:
                      issue.type === "error"
                        ? "#dc2626"
                        : issue.type === "warning"
                        ? "#d97706"
                        : "#2563eb",
                  },
                ]}
              >
                {issue.type}
              </Text>
              <View style={styles.issueContent}>
                <Text style={styles.issueMsg}>{issue.message}</Text>
                {issue.details && (
                  <Text style={styles.issueCat}>{issue.details}</Text>
                )}
                <Text style={styles.issueCat}>{issue.category}</Text>
              </View>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by AlChemist_SEO • Professional SEO Audit Tool
        </Text>
      </Page>
    </Document>
  );
}

export async function POST(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { auditId, url, score, grade, issues, pagesAudited } = body;

    let companyName = "AlChemist_SEO";
    if (userId) {
      const user = await prisma.user.findUnique({
        where: { clerkId: userId },
        include: { whiteLabel: true },
      });
      if (user?.whiteLabel?.companyName) {
        companyName = user.whiteLabel.companyName;
      }
    }

    let resolvedIssues: { type: string; category: string; message: string; details?: string }[];
    if (Array.isArray(issues)) {
      resolvedIssues = issues;
    } else if (auditId) {
      const run = await prisma.auditRun.findFirst({
        where: { id: auditId },
      });
      resolvedIssues = run ? (JSON.parse(run.issues) as { type: string; category: string; message: string; details?: string }[]) : [];
    } else {
      resolvedIssues = [];
    }

    const doc = (
      <AuditPDF
        companyName={companyName}
        url={url || "Unknown"}
        score={score ?? 0}
        grade={grade || "F"}
        issues={resolvedIssues}
        pagesAudited={pagesAudited ?? 1}
      />
    );

    const pdfBuffer = await renderToBuffer(doc);
    const pdfBytes = Buffer.isBuffer(pdfBuffer)
      ? new Uint8Array(pdfBuffer.buffer, pdfBuffer.byteOffset, pdfBuffer.byteLength)
      : new Uint8Array(pdfBuffer as ArrayBuffer);

    return new NextResponse(pdfBytes as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="seo-audit-${Date.now()}.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF" },
      { status: 500 }
    );
  }
}
